Class_10/BurgerApp.Refactored fnl/BurgerApp.REFACTORED/Controllers/BurgerController.cs
using BurgerApp.SERVICES.Interfaces;
using BurgerApp.VIEWMODELS.BurgerViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.REFACTORED.Controllers
{
    public class BurgerController : Controller
    {
        private IBurgerService _burgerService;

        public BurgerController(IBurgerService burgerService)
        {
            _burgerService = burgerService;
        }

        public IActionResult Index()
        {
            List<BurgerDetailsViewModel> burgerDetailsViewModels = _burgerService.GetAllBurgers();
            return View(burgerDetailsViewModels);
        }

        public IActionResult AddBurger()
        {
            BurgerViewModel burgerViewModel = new();
            return View(burgerViewModel);
        }

        [HttpPost]
        public IActionResult AddBurgerPost(BurgerViewModel burgerViewModel)
        {
            if (burgerViewModel == null)
            {
                return View("Error");
            }

            try
            {
                _burgerService.AddBurger(burgerViewModel);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }

        }

        public IActionResult EditBurger(int? id)
        {
            if (id == null)
            {
                return View("ResourceNotFound");
            }

            return View(_burgerService.GetBurgerById(id.Value));
        }

        [HttpPost]
        public IActionResult EditBurgerPost(BurgerViewModel burgerViewModel)
        {
            if (burgerViewModel == null)
            {
                return View("Error");
            }
            try
            {
                _burgerService.EditBurger(burgerViewModel);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        public IActionResult DeleteBurger(int? id)
        {
            if (id == null)
            {
                return View("ResourceNotFound");
            }

            try
            {                
                return View(_burgerService.GetBurgerById(id.Value));
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        public IActionResult ConfirmDelete(int? id)
        {
            if (id == null)
            {
                return View("ResourceNotFound");
            }

            try
            {
                _burgerService.DeleteBurgerById(id.Value);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }





    }
}

Class_10/BurgerApp.Refactored fnl/BurgerApp.REFACTORED/Controllers/OrderController.cs
using BurgerApp.SERVICES.Interfaces;
using BurgerApp.VIEWMODELS.OrderViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.REFACTORED.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IUserService _userService;
        private IBurgerService _burgerService;

        public OrderController(IOrderService orderService, IUserService userService, IBurgerService burgerService)
        {
            _orderService = orderService;
            _userService = userService;
            _burgerService = burgerService;
        }

        public IActionResult Index()
        {
            List<OrderDetailsViewModel> orderDetailsViewModels = _orderService.GetAllOrders();
            return View(orderDetailsViewModels);
        }

        public IActionResult AddOrder()
        {
            ViewBag.Users = _userService.GetUsersForDD();

            OrderViewModel orderViewModel = new();
            return View(orderViewModel);
        }

        public IActionResult AddOrder2(OrderViewModel orderViewModel)
        {

            ViewBag.Burgers = _burgerService.GetBurgersForDD();

            return View(orderViewModel);
        }

        [HttpPost]
        public IActionResult AddOrderPost(OrderViewModel orderViewModel)
        {
            if (orderViewModel == null)
            {
                return View("Error");
            }

            OrderViewModel finalOrderViewModel = _orderService.AddBurgerNamesAndNumberToOrderViewModel(orderViewModel);
            _orderService.AddOrder(finalOrderViewModel);
            return RedirectToAction("Index");
        }

        public IActionResult EditOrder(int? id)
        {
            ViewBag.Users = _userService.GetUsersForDD();
            ViewBag.Burgers = _burgerService.GetBurgersForDD();

            if (id == null || id <= 0)
            {
                return View("ResourceNotFound");
            }

            try
            {
                OrderViewModel orderViewModel = _orderService.GetOrderByIdToViewModel(id.Value);
                return View(orderViewModel);
            }
            catch (Exception ex)
            {
                return View("ResourceNotFound");
            }

        }

        public IActionResult EditOrder2(OrderViewModel orderViewModel)
        {
            ViewBag.Burgers = _burgerService.GetBurgersForDD();

            if (orderViewModel == null)
            {
                return View("ResourceNotFound");
            }
                        
            return View(orderViewModel);
        }

        [HttpPost]
        public IActionResult EditOrderPost(OrderViewModel orderViewModel)
        {
            OrderViewModel finalOrderViewModel = _orderService.AddBurgerNamesAndNumberToOrderViewModel(orderViewModel);

            if (finalOrderViewModel == null || finalOrderViewModel.NumberOfBurgers < 0)
            {
                return View("ResourceNotFound");
            }

            if (finalOrderViewModel.NumberOfBurgers == 0)
            {
                _orderService.RemoveBurgerOrdersFromViewModel(finalOrderViewModel);
                _orderService.DeleteOrderById(finalOrderViewModel.Id);
                return RedirectToAction("Index");
            } // ??????????????

            //if (orderViewModel.NumberOfBurgers > orderViewModel.BurgerOrders.Count)
            //{
            //    return View("EditOrder2", orderViewModel);
            //}

            _orderService.EditOrder(finalOrderViewModel);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteOrder(int id)
        {
            if (id == null)
            {
                return View("ResourceNotFound");
            }

            try
            {
                OrderDetailsViewModel orderDetailsViewModel = _orderService.GetOrderById(id);
                return View(orderDetailsViewModel);
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        public IActionResult ConfirmDelete(int? id)
        {
            if(id == null)
            {
                return View("ResourceNotFound");
            }

            try
            {                
                _orderService.DeleteOrderById(id.Value);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }


    }
}

Class_10/BurgerApp.Refactored fnl/BurgerApp.REFACTORED/Views/Shared/ResourceNotFound.cshtml
<h3>The resource you're looking for has not been found!</h3>

Class_10/BurgerApp.Refactored fnl/BurgerApp.REFACTORED/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerApp.REFACTORED</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerApp.REFACTORED.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BurgerApp.REFACTORED</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Burger" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Show orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BurgerApp.REFACTORED - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>